### PR TITLE
RICORN KINGDOM❗

### PR DESCRIPTION
**Pull request by PRoyale**
Imagine making v3.0 without the 3 💀

 ̶N̶o̶t̶e̶:̶ ̶u̶s̶e̶s̶ ̶u̶p̶s̶i̶d̶e̶ ̶d̶o̶w̶n̶ ̶P̶i̶r̶a̶n̶h̶a̶ ̶P̶l̶a̶n̶t̶,̶ ̶w̶h̶i̶c̶h̶ ̶a̶r̶e̶ ̶n̶o̶t̶ ̶f̶u̶l̶l̶y̶ ̶i̶m̶p̶l̶e̶m̶e̶n̶t̶e̶d̶.̶ ̶J̶u̶s̶t̶ ̶l̶o̶o̶k̶ ̶o̶u̶t̶ ̶f̶o̶r̶ ̶d̶a̶t
Update: they seem to work pretty fine now

### CODE REVIEW

**Comment by terminalarch** [comment]
3.1 take it or leave it

**Comment by PRoyale** [comment]
how about 3.3

**Comment by terminalarch** [comment]
ok

**Comment by terminalarch** [comment]
small problem but you didnt put it in level select

**Comment by terminalarch** [comment]
Going to make this into 4.0

**Pull request merged**
